FROM python:3.11

#WORKDIR /app/src 

#COPY ./src /app/src


WORKDIR /app

ENV PYTHONPATH="/app/:$PYTHONPATH"

COPY ./requirements/minimal.txt /app/requirements.txt

RUN pip3 install -r /app/requirements.txt
RUN pip3 install pydantic-settings==2.1.0 uvicorn

EXPOSE 8000

CMD ["uvicorn", "src.frontend.api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
